# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "http://localhost:1313/"
title = "A personal weblog by Jack Baty"
enableRobotsTXT = true
enableEmoji = true
#theme = "jane"

hasCJKLanguage = false     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 10              # Number of articles displayed on the homepage  # 首页每页显示的文章数
rssLimit = 20             # Limit Entry Count to Rss file # 限制 Rss 文章输出数量
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: author.name ↓        # 默认为下面配置的author.name ↓


# Highlight options.
# See https://gohugo.io/content-management/syntax-highlighting/
PygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
PygmentsUseClasses = true # Use CSS classes to format highlighted code
PygmentsCodefencesGuessSyntax = true
PygmentsOptions = "linenos=table"

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "en"           # Default language to use
[languages.en]
  languageCode = "en"

[author]                  # essential                     # 必需
  name = "Jack Baty"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu              # 配置目录
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Categories"
  weight = 40
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "Wiki"
  weight = 50
  url = "https://rudimentarylathe.wiki"
[[menu.main]]
  name = "Photo blog"
  weight = 60
  url = "https://copingmechanism.com/"


[params]
  since = "2020"            # Site creation time          # 站点建立时间
  homeFullContent = true   # if false, show post summaries on home page. Otherwise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = "Jack baty"        # default: the title value    # 默认值: 上面设置的title值
  keywords = ["Hugo", "theme","jane"]
  description = "Hugo theme jane example site."

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "January 2, 2006"
  dateFormatToUseArchives = "2006-01-02"
  dateFormatToUseTaxonomy = "2006-01-02"

  showAuthorInfo = false # show author info below the article


  # paginate of archives, tags and categories             # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
  archive-paginate = 300

  # paginate style, default use numbered pagination links
  # if true, use original "Previous" and "Next" links.
  paginateOriginalStyle = true




  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = false                                                                            # 是否开启目录
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe            # 是否启用PhotoSwipe（图片可点击）
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = ['custom.css']            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file


  [params.social]                                         # 社交链接
    a-email = "mailto:jack@baty.net"
    b-stack-overflow = ""
    c-twitter = "https://twitter.com/jackbaty"
    d-facebook = ""
    e-linkedin = ""
    f-google = ""
    g-github = "http://localhost:1313"
    h-weibo = ""
    i-zhihu = ""
    j-douban = ""
    k-pocket = ""
    l-tumblr = ""
    m-instagram = "https://instagram.com/mrjackbaty"
    n-gitlab = ""
    o-goodreads = "http://localhost:1313"
    p-coding = ""
    q-bilibili = ""
    r-codeforces = ""
    s-mastodon = "https://mastodon.technology/@jackbaty"
    t-youtube = ""
    u-twitch = ""

  [params.commento] # Commento is a feature rich lightweight comment system oriented on privacy (https://commento.io/)
    enable = true
    url = "https://comments.baty.net"

[module]
[[module.imports]]
    #path = "github.com/jackbaty/CodeIT"
    path = "github.com/jackbaty/hugo-theme-jane"
    disabled = false


[permalinks]
post = "/:year/:title/"
